language: python
env:
  global:
  - JEKYLL_ENV=production
  - PLACE=za-wc011
  - secure: Hgaog5KTO3dOi0FR+Hy3Kmu6Z/7GZ1dbl5S7b3zHm/8mYOeMBab7U4aY6geRAPiEcyWFxbxe4kwBtzmWjQWi0W717tSnqQTWPBPZWU6MA1vC7iWm+dttydi4eYk1PTosKRCMEMFKVECJ9VTHXCkRtEolMNvJ/QsNv3k2+724sPh/arcRxc2L0XJAKN4IxZ13Z7sUugzFseavsoDy0UBJfr6dTle8rsxZuO+1oLj1xBNWg+m/0i78+N+/SwRIVhYx5JlwR5cA2sY3ga/aNNwRrXfRwJZqZ/rb9kigKGAGCSd9OkURiiZ/12OLEWuEowibpj9tmU3+ur306Y8TNlVWNRE7IoNhbBbjOc+J2YEh0txLjDRHQV1JsXevzrYxJNf/UeYW2NxgmaOJrnUZ2UeTK275n1m9+BOwRjXmXND0MTMgkIuHUGYv7B9nHCN8y/jTC/MODHeba5VuMsHAXxstnId8kiTKsTUBRaKudG5SWixblA8q8CEfmalC9wt5WNFwy1fMuisPog9Tx2IIIJNQdiY1PyWebvCcys6vmOH2ZiOWEF9/VFp+r50oAbDZ3nPvNN+D21Sbvnn5u85C3IaOgvSiTE8DMbYSDS1DOF8NGWyPGqHpJatOjjvYr7d96EprxICXuCDSc4I9EMi+FlvIV9EOsHZEX55OAMvS3u/rFTo=
  - secure: G91gzXEqE+bXXutgZmyoBcziSlr0v1Yx/crdiDZg4x0D6V2P2vD/xi0VSGSv3vHlpOBSZJJ616sEMIWrjsV2GRHqvWj1pd4de4zFOp9Yp/zAwoB+OXMGrjw+bpeeoj6q5HMQiTdg0MuNrixcPlR0E4mSeMPP7EzyFIXOZInu+ln573JWbWxLJWiMt6dOj4xPNYgJoAOCynYZcxJPrv+5yd6spR5V9cv0yNWv3YGdZXdONKitB/MjyED0Iqf1SpMAzLV3ZcyN5ZY3mRaELaiXYmtlK2/RTC/rGRlspMmJ5C9Ia9J5c0TB3KCCtUhSB6+gBDsJN6Ys3XN1fT1ahf/rryw3YdMC5Hn+AJTboJvA4YfA2KC2YIGgURlAkriqNa7DRPcEaR8pjloivLTBgNkCdVqCBLAPZYE6nICvrZ4jDedpU6spFaQMMZVKtPGuzhJcR2RYX96W9OKNskVEMZGOQ0uSmOq4aZpnenPxRf06/dQZuAyMUGyB+VkbpaYNa+4hkve2o0hY76F06Y5ikO4gb3Wv4dTPLeCjGp6LYuXKAHUl4f6EtpVibjs50FPQ79FyO/MH1fqr6YPyjdUyyTjgrYESocR7hiTr/99mNdgUAomQJxPD5E1xbDyxf0i1oV0N7yeWotRc1ceq7vGi78XbAqH9TENFvnRzYnUyfqnkkTU=
install:
- git clone --depth 1 https://github.com/laws-africa/openbylaws-microsite.git build
- cd build
- pip install -r requirements.txt
- bundle install
- python bin/place.py $PLACE
script: bundle exec jekyll build --trace
deploy:
  provider: pages
  local_dir: build/_site
  target_branch: gh-pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: matzikama.openbylaws.org.za
  on:
    branch: master
